spring:
  datasource:
    url:
    username: root
    password: Rootizm5eeveJakqr12345!
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
        cache: false
        mode: LEGACYHTML5
        prefix: classpath:/templates/

  redis:
        host: 127.0.0.1
        port: 6379
        jedis:
          pool:
            max-active: 100
            max-idle: 10
            max-wait: 100000
        timeout: 5000
        database: 0 #默认是索引为0的数据库

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  resources:
    static-locations: classpath:static/,file:static/


  data:
      elasticsearch:
              cluster-name: es-geekdaily #默认为elasticsearch
              cluster-nodes: 172.31.247.246:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
  #           cluster-nodes: 120.79.197.131:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
              properties:
                  path:
                    logs: ./elasticsearch/log #elasticsearch日志存储目录
                    data: ./elasticsearch/data #elasticsearch数据存储目录

server:
#  port: 80
  port: 443
  ssl:
    key-store: classpath:214828842760447.pfx
    key-store-password: 214828842760447
    keyStoreType: PKCS12
#  ssl:
#      key-store: classpath:214828842760447.pfx
#      key-store-password: 214828842760447
#      keyStoreType: PKCS12

#  use-forward-headers: true
#  tomcat:
#    remote-ip-header: x-forwarded-for
#    protocol-header: x-forwarded-proto
#    port-header: X-Forwarded-Port
#    #其它设置是让Tomcat去Http头信息去获取协议信息，而不是从HttpServletRequest

  servlet:
    context-path: /geekdaily
