spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geekdaily?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#    自动执行sql脚本
#    schema: classpath:import.sql
#    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/templates/
#      suffix: .html

#  redis:
#      host: 127.0.0.1
#      port: 6379
#      jedis:
#        pool:
#          max-active: 100
#          max-idle: 10
#          max-wait: 100000
#      timeout: 5000
#      database: 0 #默认是索引为0的数据库

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  resources:
      static-locations: classpath:static/,file:static/

#adduser  jerry    passwoed   liulei0911
#  data:
#       elasticsearch:
#              cluster-name: es-geekdaily #默认为elasticsearch
#              cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
##              cluster-nodes: 120.79.197.131:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
#              properties:
#                  path:
#                    logs: ./elasticsearch/log #elasticsearch日志存储目录
#                    data: ./elasticsearch/data #elasticsearch数据存储目录

server:
  port: 8013
#  port: 443
#  ssl:
#      key-store: classpath:214828842760447.pfx
#      key-store-password: TMKT1HpS
#      keyStoreType: PKCS12
  servlet:
    context-path: /geekdaily
